apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4-kustomize
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app4-kustomize
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
