apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/deployment.yaml
- resources/service.yaml
configMapGenerator:
- envs:
  - configs/config.env
  name: example-app-configmap-env
- files:
  - configs/config.yaml
  name: example-app-configmap-file
secretGenerator:
- envs:
  - secrets/secret.env
  name: example-app-secret-env
