apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    app.kubernetes.io/name: example-app
    app.kubernetes.io/instance: example-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
      app.kubernetes.io/instance: example-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
        app.kubernetes.io/instance: example-app
    spec:
      containers:
        - name: example-app
          image: asia.gcr.io/poc-innovation-iot/training-kube/example-app:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: example-app-configmap-env
            - secretRef:
                name: example-app-secret-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 400m
              memory: 256Mi
          volumeMounts:
            - name: example-app-configmap-file
              mountPath: /configs/config.yaml
              subPath: config.yaml

      volumes:
        - name: example-app-configmap-file
          configMap:
            name: example-app-configmap-file
