apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-nginx
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: TEST
              value: someconfigenv
          volumeMounts:
            - name: first-test-config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: first-test-config-volume
          configMap:
            name: first-test-config
