apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app2-config-volume
              mountPath: /app/config
              readOnly: true
            - name: app2-secret-volume
              mountPath: /app/secret
              readOnly: true
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
      volumes:
        - name: app2-config-volume
          configMap:
            name: app2-configmap
        - name: app2-secret-volume
          secret:
            secretName: app2-secret
